/*=============================================================================
 *  Class:        ValidationResult.java
 *  Package:      paint.shared.validate
 *
 *  PURPOSE:
 *    Encapsulates the outcome of validation operations within the PAINT
 *    framework, collecting errors, warnings, and informational messages
 *    into a unified result object.
 *
 *  DESCRIPTION:
 *    • Stores categorized messages (errors, warnings, infos) generated by
 *      various validator classes.
 *    • Provides merging capability for combining results from multiple
 *      validation passes.
 *    • Maintains an optional string report for formatted summaries.
 *
 *  RESPONSIBILITIES:
 *    • Accumulate and manage structured validation results.
 *    • Provide read-only accessors for validation message lists.
 *    • Support merging, summarization, and reporting operations.
 *
 *  USAGE EXAMPLE:
 *    ValidationResult result = validator.validate(file);
 *    if (result.hasErrors()) {
 *        System.err.println(result.getReport());
 *    } else {
 *        System.out.println("✔ Validation passed");
 *    }
 *
 *  DEPENDENCIES:
 *    – java.util.{List, ArrayList, Collections}
 *
 *  AUTHOR:
 *    Hans Bakker
 *
 *  MODULE:
 *    paint-shared-utils
 *
 *  UPDATED:
 *    2025-12-31
 *
 *  COPYRIGHT:
 *    © 2025 Hans Bakker. All rights reserved.
=============================================================================*/

package paint.shared.validate;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

/**
 * Represents the aggregated result of one or more validation processes.
 * Stores categorized message lists (errors, warnings, and infos) and
 * provides convenience methods for merging and reporting.
 */
public final class ValidationResult {

    // ───────────────────────────────────────────────────────────────────────────────
    // FIELDS
    // ───────────────────────────────────────────────────────────────────────────────

    private final List<String> errors   = new ArrayList<>();
    private final List<String> warnings = new ArrayList<>();
    private final List<String> infos    = new ArrayList<>();
    private String report               = null;

    // ───────────────────────────────────────────────────────────────────────────────
    // MESSAGE ADDERS
    // ───────────────────────────────────────────────────────────────────────────────

    /**
     * Adds a new error message to the validation result.
     *
     * @param message descriptive text of the validation error
     */
    public void addError(String message) {
        errors.add(message);
    }

    /**
     * Adds a new warning message to the validation result.
     *
     * @param message descriptive text of the validation warning
     */
    public void addWarning(String message) {
        warnings.add(message);
    }

    // ───────────────────────────────────────────────────────────────────────────────
    // ACCESSORS
    // ───────────────────────────────────────────────────────────────────────────────

    /**
     * Returns an immutable view of all recorded errors.
     */
    public List<String> getErrors() {
        return Collections.unmodifiableList(errors);
    }

    /**
     * Returns an immutable view of all recorded warnings.
     */
    public List<String> getWarnings() {
        return Collections.unmodifiableList(warnings);
    }

    /**
     * Returns an immutable view of all informational messages.
     */
    public List<String> getInfos() {
        return Collections.unmodifiableList(infos);
    }

    // ───────────────────────────────────────────────────────────────────────────────
    // STATE CHECKS
    // ───────────────────────────────────────────────────────────────────────────────

    /**
     * Checks if the validation result contains one or more errors.
     */
    public boolean hasErrors() {
        return !errors.isEmpty();
    }

    /**
     * Checks if the validation result contains warnings.
     */
    public boolean hasWarnings() {
        return !warnings.isEmpty();
    }

    /**
     * Checks if the validation includes informational messages.
     */
    public boolean hasInfos() {
        return !infos.isEmpty();
    }

    /**
     * Determines whether the validation result is completely valid.
     */
    public boolean isValid() {
        return errors.isEmpty();
    }

    // ───────────────────────────────────────────────────────────────────────────────
    // MERGE & REPORTING
    // ───────────────────────────────────────────────────────────────────────────────

    /**
     * Merges another {@link ValidationResult} into this one.
     */
    public void merge(ValidationResult other) {
        if (other == null) {
            return;
        }

        this.errors.addAll(other.getErrors());
        this.warnings.addAll(other.getWarnings());
        this.infos.addAll(other.getInfos());

        if (other.report != null) {
            if (this.report == null) {
                this.report = other.report;
            } else {
                this.report += "\n" + other.report;
            }
        }
    }

    /**
     * Sets the report string for this validation result.
     */
    public void setReport(String report) {
        this.report = report;
    }

    /**
     * Returns the current report string, if set.
     */
    public String getReport() {
        return report;
    }

    // ───────────────────────────────────────────────────────────────────────────────
    // OUTPUT
    // ───────────────────────────────────────────────────────────────────────────────

    @Override
    public String toString() {

        // Prefer explicit report if set
        if (report != null) {
            return report;
        }

        StringBuilder sb = new StringBuilder();

        if (hasErrors()) {
            sb.append("❌ ERRORS:\n");
            for (String e : errors) {
                sb.append("  • ").append(e).append('\n');
            }
        }

        if (hasWarnings()) {
            sb.append("⚠️  WARNINGS:\n");
            for (String w : warnings) {
                sb.append("  • ").append(w).append('\n');
            }
        }

        if (hasInfos()) {
            sb.append("ℹ️  INFO:\n");
            for (String i : infos) {
                sb.append("  • ").append(i).append('\n');
            }
        }

        if (!hasErrors() && !hasWarnings()) {
            sb.append("✔ No issues found");
        }

        return sb.toString();
    }
}