name: Build and Release

on:
  push:
    tags:
      - 'v*.*.*'      # Run when you push a version tag like v1.3.0

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Check out your source code
      - uses: actions/checkout@v4

      # 2. Set up Java 8 (Temurin distribution)
      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'temurin'

      # 3. Build your project with Maven
      - name: Build with Maven
        run: mvn -B clean package -DskipTests

      # 4. Collect all fat JARs from submodules
      - name: Collect release JARs
        run: |
          mkdir -p release
          find . -name "*-jar-with-dependencies.jar" -exec cp {} release/ \;

      # 5. Publish GitHub Release and attach JARs
      - name: Publish GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: release/*
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}